# policy-as-code/gatekeeper/templates/nolb_template.yaml
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: disallowpubliclb
spec:
  crd:
    spec:
      names:
        kind: DisallowPublicLB
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package disallowpubliclb
        violation[{"msg": msg}] {
          svc := input.review.object
          svc.kind == "Service"
          svc.spec.type == "LoadBalancer"
          msg := "policy violation"
        }
